// team8-integration5/src/components/AppFooter.vue
<template>
  <footer class="app-footer">
    <p>&copy; 2024 Mart.ps.</p>
  </footer>
</template>

<script>
export default {
  name: 'AppFooter'
};
</script>

<style scoped lang="scss">
.app-footer {
  background-color: #333;
  color: #fff;
  text-align: center;
  padding: 20px;
  position: fixed;
  width: 100%;
  bottom: 0;
  
  p {
    margin: 0;
  }
}
</style>

// my-project/src/lit-app/app-footer.js
import { LitElement, html, css } from 'lit';

class AppFooter extends LitElement {
  static styles = css`
    .app-footer {
      background-color: #333;
      color: #fff;
      text-align: center;
      padding: 20px;
      position: flex;
      width: 100%;
      bottom: 0;
      margin-top:50px;
    }

    .app-footer p {
      margin: 0;
      font-size:18px;

    }
  `;

  render() {
    return html`
      <footer class="app-footer">
        <p>&copy; 2024 Mart.ps.</p>
      </footer>
    `;
  }
}

customElements.define('app-footer', AppFooter);
