// Desktop/comp-project/src/components/AppHeader.vue
<template>
  <header class="app-header">
    <nav>
      <ul>
        <li><router-link to="/">Login</router-link></li>
         <li><router-link to="/RegistrationPage">Register</router-link></li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  name: 'AppHeader'
};
</script>

<style scoped lang="scss">
.app-header {
  background-color: #333;
  color: #fff;
  padding: 20px;
  
  nav ul {
    display: flex;
    justify-content: center;
    list-style: none;
    padding: 0;
    
    li {
      margin: 0 15px;
      
      a {
        color: #fff;
        text-decoration: none;
        &:hover {
          text-decoration: underline;
        }
      }
    }
  }
}
</style>

// my-project/src/lit-app/app-header.js
import { LitElement, html, css } from 'lit';

class AppHeader extends LitElement {
  static styles = css`
    .app-header {
      background-color: #333;
      color: #fff;
      padding: 20px;
    }

    nav ul {
      display: flex;
      justify-content: center;
      list-style: none;
      padding: 0;
    }

    nav ul li {
      margin: 0 15px;
      font-size:18px;
    }

    nav ul li a {
      color: #fff;
      text-decoration: none;
    }

    nav ul li a:hover {
      text-decoration: underline;
    }
  `;

  render() {
    return html`
      <header class="app-header">
        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/">category</a></li>
            <li><a href="/">Login</a></li>
            <li><a href="/"></a></li>

          </ul>
        </nav>
      </header>
    `;
  }
}

customElements.define('app-header', AppHeader);
